<a href="https://colab.research.google.com/github/suneelshrestha/mlclass/blob/main/introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

What we will cover?
*   ✅Creating arrays
*   ✅Multidimesnional array
*   Randomly generated arrays
*   Element wise operation
*   Summarizing operations

## creating arrays


In [1]:
import numpy as np

In [2]:
#create an array with all the elements to be  Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
#create an array with all the elements to be one
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
# create an array of size with all elements 3
#np.full(size,elements)
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [5]:
#create random array
np.array({1, 2, 3, 4, 5})

array({1, 2, 3, 4, 5}, dtype=object)

In [7]:
#creating array starting form one element to specific element
#np.arange(starting element,ending element-1)
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
#create an array with evenly spaced numbers within a specified range
#np.linspace(staring_element,ending_element,no_to_divide_into)
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## multidimensional arrays

In [9]:
#creating 3*5 matrix with elements zero
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
#creating 3*3 matrix with element one
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
#creating 3*3 matrix using array
a= np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
#replacing the element of the array
# a[0:1]=20
a[0,1]=20
print(a)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [52]:
#replacing the last element of the array
# a[2:3]=1
# a[2]=1
a[2]=[1, 1, 1]
print(a)

[[ 1 20  3]
 [ 4  5  6]
 [ 1  1  1]]


In [53]:
a[:, 2]=[2, 2, 2]
print(a)

[[ 1 20  2]
 [ 4  5  2]
 [ 1  1  2]]


In [59]:
#creating 3*3 martix of element 10
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## Randomly generated arrays

- NumPy can create arrays filled with random numbers
- to ensire the reproducibility , you can seed using ```np.random.seed()``` seed using the exact same random numbers for each executions.
-if you remove or change the seed vlues the sequence of random numbers will be chnaged.

In [60]:
np.random.rand(5)

array([0.6430371 , 0.0431241 , 0.30246429, 0.73684397, 0.74527226])

In [80]:
#seed makes the random value to be same every time executed
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [81]:
np.random.rand(5, 2)

array([[0.6851502 , 0.21165334],
       [0.31726607, 0.2672994 ],
       [0.12050632, 0.9968569 ],
       [0.08043969, 0.28459975],
       [0.5352502 , 0.84580211]])

In [85]:
#creating random integer
# np.random.randint(low_value,high_value,no_of_elements)
# np.random.randint(1,9,5)
# np.random.randint(low=0, high=9, size=(5,5))
np.random.randint(1, 9, size=(5,5))

array([[4, 7, 4, 3, 6],
       [1, 4, 4, 8, 4],
       [1, 7, 6, 5, 7],
       [4, 4, 8, 5, 1],
       [4, 2, 8, 8, 1]])